config/routes.rb
Rails.application.routes.draw do

  resources :parks
  root 'welcomes#index'
  get '/note',to: "welcomes#note"
  get '/test',to: "welcomes#test"
  get '/jstest',to: "welcomes#jstest"
  get '/jstest2',to: "welcomes#jstest2"

end

app/models/park.rb
class Park < ActiveRecord::Base

    geocoded_by :address, :latitude => :wgsy, :longitude => :wgsx

    def self.search(search)
        where('parkname LIKE ?', "%#{search}%")
    end
end

app/models/ubike.rb
class Ubike < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
    before_action :set_park, only: [:show, :edit, :update, :destroy]
    require 'rest-client'
    require 'json'
    # GET /parks
    # GET /parks.json
    #def index
        #@parks = Park.all
          #@parks = Park.search(params[:search])
        #get_json
    #end

    def index
      p '---userx--'
      p params[:userx]
      p '---usery--'
      p params[:usery]
      @parks = Park.all.order(:id)
      if params[:search] && params[:order]
        #@parks = Park.search(params[:search]).order(wgsx: params[:order])
        @parks = Park.search(params[:search]).order(:id)
      elsif params[:order]
        #@parks = Park.all.order(wgsx: params[:order])
        @parks = Park.all.order(:id)
      end
      # get_json_create
      get_json
    end

    def get_json
        url = 'http://data.tycg.gov.tw/api/v1/rest/datastore/0daad6e6-0632-44f5-bd25-5e1de1e9146f?format=json'
        response = RestClient.get(url)
        price_data = JSON.parse(response)
        # 以下為Json格式
        # p JSON.parse(response)
        # p price_data["parkName"]
        # price_data.each do |u|
        #Park.destroy_all
        price_data['result']['records'].each do |u|
            @park = Park.all
            @park.each do |park|
                if park.parkid == u['parkId'].to_s
                    p park.parkname
                    p u['parkName'].to_s
                    p u['surplusSpace'].to_s
                    park.surplusspace = u['surplusSpace'].to_s

                    now_t = Time.now + (60 * 60 * 8)
                    park.updatetime = now_t.to_formatted_s(:db).to_s
                    park.wgsx = u['wgsX'].to_f
                    park.wgsy = u['wgsY'].to_f

                    #park.updatetime = Time.now.localtime.to_formatted_s(:db).to_s
                    park.save


                #else
                #  Park.create(
                #      _id: u['_id'].to_s,
                #      parkid: u['parkId'].to_s,
                #      areaid: u['areaId'].to_s,
                #      areaname: u['areaName'].to_s,
                #      parkname: u['parkName'].to_s,
                #      introduction: u['introduction'].to_s,
                #      address: u['address'].to_s,
                #      totalspace: u['totalSpace'].to_s,
                #      surplusspace: u['surplusSpace'].to_s,
                #      payguide: u['payGuide'].to_s,
                #      updatetime: u['updatetime'].to_s,
                #      wgsx: u['wgsX'].to_s,
                #      wgsy: u['wgsY'].to_s
                #  )
                end
            end
        end
    end
    p Time.now
    def get_json_create
      url = 'http://data.tycg.gov.tw/api/v1/rest/datastore/0daad6e6-0632-44f5-bd25-5e1de1e9146f?format=json'
      response = RestClient.get(url)
      price_data = JSON.parse(response)
      Park.destroy_all
      price_data['result']['records'].each do |u|
      Park.create(
          _id: u['_id'].to_s,
          parkid: u['parkId'].to_s,
          areaid: u['areaId'].to_s,
          areaname: u['areaName'].to_s,
          parkname: u['parkName'].to_s,
          introduction: u['introduction'].to_s,
          address: u['address'].to_s,
          totalspace: u['totalSpace'].to_s,
          surplusspace: u['surplusSpace'].to_s,
          payguide: u['payGuide'].to_s,
          #updatetime: u['updatetime'].to_s,
          updatetime: Time.new.to_formatted_s(:db).to_s,
          wgsx: u['wgsX'].to_f,
          wgsy: u['wgsY'].to_f
      )
    end
    end
    # if u["type"].to_s != nil
    # p u["_id"].to_s
    # end
    # a = Park.find_by_park_id(u['_id'])
    # p a
    # if a.nil?
    #    Park.create(
    #        _id: u['_id'].to_s,
    #        surplusspace: u['surplusSpace'].to_s,
    #        updatetime: u['updatetime'].to_s
    #    )

    # else
    #    Park.update(
    #        _id: u['_id'].to_s,
    #        surplusspace: u['surplusSpace'].to_s,
    #        updatetime: u['updatetime'].to_s
    #    )
    # end
    # crop_number: u["作物代號"],crop_name: u["作物名稱"],
    # market_name: u["市場代號"],market_number: u["市場名稱"],
    # on_price: u["上價"],the_price: u["中價"],by_price: u["下價"],
    # avg_price: u["平均價"],tranding_price: u["交易量"])

    # GET /parks/1
    # GET /parks/1.json
    def show
      respond_to do |format|
        format.html
        format.js
      end
    end

    # GET /parks/new
    def new
        @park = Park.new
    end

    # GET /parks/1/edit
    def edit
    end

    # POST /parks
    # POST /parks.json
    def create
        @park = Park.new(park_params)

        respond_to do |format|
            if @park.save
                format.html { redirect_to @park, notice: 'Park was successfully created.' }
                format.json { render :show, status: :created, location: @park }
            else
                format.html { render :new }
                format.json { render json: @park.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /parks/1
    # PATCH/PUT /parks/1.json
    def update
        respond_to do |format|
            if @park.update(park_params)
                format.html { redirect_to @park, notice: 'Park was successfully updated.' }
                format.json { render :show, status: :ok, location: @park }
            else
                format.html { render :edit }
                format.json { render json: @park.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /parks/1
    # DELETE /parks/1.json
    def destroy
        @park.destroy
        respond_to do |format|
            format.html { redirect_to parks_url, notice: 'Park was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_park
        @park = Park.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def park_params
        params.require(:park).permit(:parkname,:address,:map_address)

    end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  layout 'welcome'
  def index
    @parks = Park.all.order(:id)
    @order = params[:order]
    wgsx = params[:lat]
    wgsy = params[:lng]

    if @order=="distance"
        @parks = Park.near([wgsx.to_f,wgsy.to_f],99).limit(6)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/views/layouts/_menu.html.erb
<!-- Navigation -->
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom navbar-background">
    <div class="container navbar-background ">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header  page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                Menu
                <i class="fa fa-bars"></i>
            </button>
            <!-- <a class="navbar-brand" href="#page-top">Parking Ba!</a> -->
            <a class="navbar-brand" href="#page-top">
                <div class="logo_rotate" id="0"><%= image_tag("packingba_logo.png") %></div>
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden ">
                    <a href="#page-top"></a>
                </li>
                <li class="page-scroll menu_li">
                <!--    <a class="menu_word" href="<!%= note_path %>">紀錄</a>  -->
                    <a class="menu_word" href="#"></a>
                </li>
                <li class="page-scroll menu_li">
                <!--    <a class="menu_word" href="#portfolio">停車場們</a>  -->
                <a class="menu_word" href="http://ebus.tycg.gov.tw/NewTaoyuan/Dybus.aspx">桃園市公車動態資訊系統</a>
                </li>
                <li class="page-scroll menu_li">
                <!--    <a class="menu_word" href="#about">說明</a>  -->
                    <a class="menu_word" href="http://openquery.tycg.gov.tw/">桃園市政府罰緩規費管理系統</a>
                </li>
                <li class="page-scroll menu_li">
                <!--    <a class="menu_word" href="<!%= note_path %>">紀錄</a>  -->
                    <a class="menu_word" href="http://traffic.tycg.gov.tw/">桃園市政府交通局</a>
                </li>

            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>
<!-- Header -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Parking Ba!</title>
        <link rel="icon" type="image/png" href="https://s3-us-west-2.amazonaws.com/nirvana2016/image/icon-03.png">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>

            <%= yield %>
    </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
    <head runat="server">
        <title>Parking Ba!</title>
        <script type='text/javascript' src='http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.1.js'></script>
        <script src="https://maps.google.com/maps/api/js?sensor=true"></script>
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

        <script src="DynaMarkerIcon.js" type="text/javascript"></script>
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no"/>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

        <!-- Theme CSS -->
        <%# <link href="css/freelancer.min.css" rel="stylesheet"> %>
        <link rel=stylesheet type="text/css" href="/stylesheets/freelancer.min.css">

        <!-- Custom Fonts -->
        <%# <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"> %>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <style>
            body,
            input {
                font-size: 9pt;
            }
            html {
                height: 100%;
            }
            body {
                height: 100%;
                margin: 0;
                padding: 0;
            }
            #map_canvas {
                height: 100%;
            }

        </style>
        <script>
            $(function () {
                //計算兩個經緯座標間的距離(Haversine公式)
                function distHaversine(p1, p2) {
                    var rad = function (x) {
                        return x * Math.PI / 180;
                    }
                    var R = 6371; // earth's mean radius in km
                    var dLat = rad(p2.lat() - p1.lat());
                    var dLong = rad(p2.lng() - p1.lng());
                    var a = Math.sin(dLat / 2) * Math.sin(dLat / 2) + Math.cos(rad(p1.lat())) * Math.cos(rad(p2.lat())) * Math.sin(dLong / 2) * Math.sin(dLong / 2);
                    var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
                    var d = R * c;
                    return parseFloat(d.toFixed(3));
                }
                //消防分局資料陣列
                var branches = [];
                //取得分局資料(含經緯座標)，存為物作陣列
                $.get("AddrList.txt", {}, function (list) {
                    var lines = list.replace(/\r/g, "").split('\n');
                    //lines[i]格式如下: 文山中隊-木柵分隊,(02)29391604,文山區木柵路2段200號,24.9890353,121.5630845
                    for (var i = 0; i < lines.length; i++) {
                        var parts = lines[i].split(',');
                        branches.push({
                            name: parts[0],
                            tel: parts[1],
                            addr: parts[2],
                            latlng: new google.maps.LatLng(parseFloat(parts[3]), parseFloat(parts[4])),
                            dist: 0
                        });
                    }
                    getGeolocation();
                });
                //取得使用者目前位罝
                function getGeolocation() {
                    if (navigator && navigator.geolocation) {
                        //getCurrentPosition屬非同步執行，要另定函數解析結果
                        navigator.geolocation.getCurrentPosition(parsePosition);
                    }
                }
                //解析getCurrentPosition傳回的結果
                function parsePosition(pos) {
                    //標示點陣列
                    var markers = [];
                    //由pos.coords取出latitude及longitude
                    var curLatLng = new google.maps.LatLng(pos.coords.latitude, pos.coords.longitude);
                    //分別計算對所有Branch的距離
                    for (var i = 0; i < branches.length; i++) {
                        var branch = branches[i];
                        branch.distance = //計算兩個LatLng間的距離
                        distHaversine(branch.latlng, curLatLng);

                    }
                    //依距離進行排序
                    branches.sort(function (a, b) {
                        if (a.distance == b.distance)
                            return 0;

                        return (a.distance > b.distance)
                            ? 1
                            : -1;
                    });
                    //設定地圖參數
                    var mapOptions = {
                        center: curLatLng,
                        mapTypeId: google.maps.MapTypeId.ROADMAP //正常2D道路模式
                    };
                    //在指定DOM元素中嵌入地圖
                    var map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
                    //使用LatLngBounds統計檢視範圍
                    var bounds = new google.maps.LatLngBounds();
                    //加入使用者所在位置
                    var marker = new google.maps.Marker({
                        position: curLatLng, title: "現在位置",
                        //借用前篇文章介紹的Canvas.toDataURL()產生動態圖檔作為圖示
                        icon: createMarkerIcon("現在位置"),
                        map: map
                    });
                    var h = [];
                    //因為已排序過，故會依距離由近到遠加入Marker
                    for (var i = 0; i < branches.length; i++) {
                        var b = branches[i];
                        //距離最近的前五名加入檢視範圍
                        if (i < 5)
                            bounds.extend(b.latlng);
                        var marker = new google.maps.Marker({
                            position: b.latlng, title: b.name, //以刻有分隊名稱的告示牌作為圖示
                            icon: createMarkerIcon(b.name.split('-')[1],
                            //距離較近的前五名為紅底，其餘為暗紅底
                            {
                                bgColor: i < 5
                                    ? 'red'
                                    : 'darkred'
                            }),
                            map: map
                        });
                    }
                    //調整檢視範圍
                    map.fitBounds(bounds);
                }
            });
        </script>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" type="image/png" href="https://s3-us-west-2.amazonaws.com/nirvana2016/image/icon-03.png">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body id="page-top" class="index div_container herder">

        <div class="container body">
          <div class="main_container">
            <%= render 'layouts/menu' %>
          </div>
        </div>
        <%= yield %>
    </body>
</html>

app/views/parks/_event.html.erb
<%= @park.parkid %><br>
<%= @park.wgsx %><br>
<%= @park.wgsy %><br>

app/views/parks/_form.html.erb
<%= form_for((@park),html: {class: "form-horizontal form-label-left"}) do |f| %>
<!--<!%= form_for([:admin, @rss.becomes(Rss)], html: {class: "form-horizontal form-label-left"}) do |f| %> -->

  <% if @park.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@park.errors.count, "error") %> prohibited this park from being saved:</h2>

      <ul>
      <% @park.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>

  <% end %>



  <div class="form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="title">
          Parkname<span class="required">*</span>
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
          <%=f.text_field :parkname,class:"form-control col-md-7 col-xs-12","data-parsley-id"=>"address",required: "required"%>
          <ul id="parsley-id-rss_title" class="parsley-errors-list"></ul>
      </div>
  </div>
  <div class="form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="title">
          Address<span class="required">*</span>
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
          <%=f.text_field :address,class:"form-control col-md-7 col-xs-12","data-parsley-id"=>"address",required: "required"%>
          <ul id="parsley-id-rss_title" class="parsley-errors-list"></ul>
      </div>
  </div>
  <div class="form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="title">
          Address for google map<span class="required">*</span>
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
          <%=f.text_field :map_address,class:"form-control col-md-7 col-xs-12","data-parsley-id"=>"map_address",required: "required"%>
          <ul id="parsley-id-rss_title" class="parsley-errors-list"></ul>
      </div>
  </div>

  <div class="form-group">
      <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
          <button type="submit" class="btn btn-success">Submit</button>
      </div>
  </div>
<% end %>

app/views/parks/edit.html.erb
<h1>Editing Park</h1>

<%= render 'form' %>

<%= link_to 'Show', @park %> |
<%= link_to 'Back', parks_path %>

app/views/parks/index.html.erb
<p id="notice"><%= notice %></p>


<%= form_tag(parks_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "請輸入停車場名..." %>
<%= submit_tag "Search" %>
<% end %>
<div id="event_area"></div>
<h1>Listing Parks</h1>

<table class="table table-striped responsive-utilities jambo_table bulk_action">
  <thead>
    <tr>
      <th>id</th>
      <th>parkid</th>
      <th>areaid</th>
      <th>areaname</th>
      <th>parkname</th>
      <th>introduction</th>
      <th>address</th>
      <th>map_address</th>
      <th>totalspace</th>
      <th>surplusspace</th>
      <th>payguide</th>
      <th>updatetime</th>
      <th>wgsx</th>
      <th>wgsy</th>
      <th>edit</th>
      <th>ajsx</th>
    <!--  <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @parks.each do |park| %>
      <tr>
        <td><%=park._id  %></td>
        <td><%=park.parkid  %></td>
        <td><%=park.areaid  %></td>
        <td><%=park.areaname %></td>
        <td><%=park.parkname  %></td>
        <td><%=park.introduction  %></td>
        <td><%=park.address  %></td>
        <td><%=park.map_address %></td>
        <td><%=park.totalspace  %></td>
        <td><%=park.surplusspace  %></td>
        <td><%=park.payguide  %></td>
        <td><%=park.updatetime  %></td>
        <td><%=park.wgsx  %></td>
        <td><%=park.wgsy  %></td>
    <!--    <td><!%= link_to 'Show', park %></td> -->
        <td><%= link_to 'Edit', edit_park_path(park) %></td>
        <td><%= link_to 'show', park_path(park), :remote => true %></td>
    <!--    <td><!%= link_to 'Destroy', park, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/parks/new.html.erb
<h1>New Park</h1>

<%= render 'form' %>

<%= link_to 'Back', parks_path %>

app/views/parks/show.html.erb
<p id="notice"><%= notice %></p>
<%= @park.parkid %>

<%= link_to 'Edit', edit_park_path(@park) %> |
<%= link_to 'Back', parks_path %>

app/views/parks/show.js.erb
$('#event_area').html("<%= escape_javascript(render :partial => 'event') %>").css({ backgroundColor: '#ffff99' });

app/views/welcomes/jstest.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>jQuery.getJSON demo</title>
  <style>
  img {
    height: 100px;
    float: left;
  }
  </style>
  <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
</head>
<body>
<br><br><br><br>
<br><br>

<br>

<div id="images"></div>

<script>
(function() {
  var flickerAPI = "http://api.flickr.com/services/feeds/photos_public.gne?jsoncallback=?";
  $.getJSON( flickerAPI, {
    tags: "mount rainier",
    tagmode: "any",
    format: "json"
  })
    .done(function( data ) {
      $.each( data.items, function( i, item ) {
        $( "<img>" ).attr( "src", item.media.m ).appendTo( "#images" );
        if ( i === 3 ) {
          return false;
        }
      });
    });
})();
</script>

</body>
</html>

app/views/welcomes/jstest2.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>jQuery.getJSON demo</title>
  <style>
  img {
    height: 100px;
    float: left;
  }
  </style>
  <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
</head>
<body>
<br><br><br><br>
<br><br>

<br>

<div id="images"></div>

<script>
  var target = "http://data.tycg.gov.tw/api/v1/rest/datastore/0daad6e6-0632-44f5-bd25-5e1de1e9146f?format=json";
  function ajaxCall(target){
  //發出 ajax call
  var data = $.ajax({
  type: "get",
  //type: "POST",
  async: true,//async設定false會變成同步請求 要完成ajax後才會繼續執行
  url: target,
  dataType: "jsonp",
  jsonpCallback:"callBackdata",
  //callback函式(jsonp的callback函式，預設是callback)
  });
  alert(data);
}
ajaxCall();
</script>

</body>
</html>

app/views/welcomes/note.html.erb
    <h1>桃園停車場查詢系統</h1>
    <h2>8/16動工，比賽時間9/24</h2>
    <h3>初始目標</h3>
    <a>第一階段(8/17)</a><br>
    <a href="http://data.tycg.gov.tw/TYCG_OPD/opendata/datalist/datasetMeta/outboundDesc?id=f4cc0b12-86ac-40f9-8745-885bddc18f79&rid=0daad6e6-0632-44f5-bd25-5e1de1e9146f" target="_blank">
      1.由路外停車資訊取回資料，格式為json
    </a><br>
    <a href="http://www.oschina.net/news/59924/free-bootstrap-templates" target="_blank">
      2.加入bootstrap-templates
    </a><br>
    <a href="http://tech.guojheng-lin.com/posts/2015/12/03/write-a-ruby-file-regularly-to-catch-crawling-web-page-data/" target="_blank">
      3.定時同步資料，利用heroku schedural
    </a>
    <br><br><br><br><br><br><br>
    <a>-----------------------------------------------------------------------------------</a>
    <h4>報名網址如下</h4>
    <a href="https://od.tycg.gov.tw/hackathon#sectionB" target="_blank">https://od.tycg.gov.tw/hackathon#sectionB</a>
    <h4>開放資料</h4>
    <a href="http://data.tycg.gov.tw/TYCG_OPD/" target="_blank">http://data.tycg.gov.tw/TYCG_OPD/</a>
    <h4>github已建立，路徑如下</h4>

    <a href="https://github.com/hidesor/parkingba" target="_blank">https://github.com/hidesor/parkingba</a>
  <!--  <ul class="nav nav-pills">
      <li role="presentation" class="active"><a href="#">Home</a></li>
      <li role="presentation"><a href="#">Profile</a></li>
      <li role="presentation"><a href="#">Messages</a></li>
    </ul>
    <button class="btn btn-default" type="submit">Button</button> -->
    <br><%= link_to "更新車位資料", parks_path %>

app/views/welcomes/test.html.erb
<!DOCTYPE html>
<html>
<body>
<p id="demo">点击这个按钮，获得您的坐标：</p>
<button onclick="getLocation()">试一下</button>
<script>
var x=document.getElementById("demo");
function getLocation()
  {
  if (navigator.geolocation)
    {
    navigator.geolocation.getCurrentPosition(showPosition);
    }
  else{x.innerHTML="Geolocation is not supported by this browser.";}
  }
function showPosition(position)
  {
  x.innerHTML="Latitude: " + position.coords.latitude +
  "<br />Longitude: " + position.coords.longitude;
  }
</script>
</body>
</html>